import { Manrope } from "next/font/google";
import "./globals.css";
import Menu from "@/components/Menu/Menu";
import Footer from "@/components/footer/Footer";

const manrope = Manrope({
  variable: "--font-manrope",
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${manrope.className} antialiased`}>
        <Menu />
        {children}
        <Footer />
      </body>
    </html>
  );
}
